/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{ts,html,css}",
    ],
    darkMode: ['selector', '[data-theme="dark"]'],
    theme: {
        extend: {
            colors: {
                primary: 'var(--md-sys-color-primary)',
                'on-primary': 'var(--md-sys-color-on-primary)',
                'primary-container': 'var(--md-sys-color-primary-container)',
                'on-primary-container': 'var(--md-sys-color-on-primary-container)',
                secondary: 'var(--md-sys-color-secondary)',
                'on-secondary': 'var(--md-sys-color-on-secondary)',
                'secondary-container': 'var(--md-sys-color-secondary-container)',
                'on-secondary-container': 'var(--md-sys-color-on-secondary-container)',
                tertiary: 'var(--md-sys-color-tertiary)',
                'on-tertiary': 'var(--md-sys-color-on-tertiary)',
                'tertiary-container': 'var(--md-sys-color-tertiary-container)',
                'on-tertiary-container': 'var(--md-sys-color-on-tertiary-container)',
                error: 'var(--md-sys-color-error)',
                'on-error': 'var(--md-sys-color-on-error)',
                background: 'var(--md-sys-color-background)',
                'on-background': 'var(--md-sys-color-on-background)',
                surface: 'var(--md-sys-color-surface)',
                'on-surface': 'var(--md-sys-color-on-surface)',
                'surface-variant': 'var(--md-sys-color-surface-variant)',
                'on-surface-variant': 'var(--md-sys-color-on-surface-variant)',
                outline: 'var(--md-sys-color-outline)',
                'surface-container-low': 'var(--md-sys-color-surface-container-low)',
            },
            fontSize: {
                'display-large': ['57px', { lineHeight: '64px', fontWeight: '600' }],
                'headline-large': ['32px', { lineHeight: '40px', fontWeight: '600' }],
                'headline-medium': ['28px', { lineHeight: '36px', fontWeight: '600' }],
                'title-large': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                'title-medium': ['16px', { lineHeight: '24px', fontWeight: '600' }],
                'title-small': ['14px', { lineHeight: '20px', fontWeight: '600' }],
                'body-large': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'body-medium': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'label-large': ['14px', { lineHeight: '20px', fontWeight: '600' }],
                'label-medium': ['12px', { lineHeight: '16px', fontWeight: '600' }],
                'label-small': ['11px', { lineHeight: '16px', fontWeight: '600' }],
            },
            borderRadius: {
                small: '4px',
                medium: '6px',
                large: '12px',
                'extra-large': '24px',
            },
            spacing: {
                'px-4': '4px',
                'px-8': '8px',
                'px-12': '12px',
                'px-16': '16px',
                'px-24': '24px',
                'px-32': '32px',
                'px-40': '40px',
                'px-48': '48px',
            },
            boxShadow: {
                'level-0': 'none',
                'level-1': '0px 1px 3px 1px rgba(0, 0, 0, 0.15), 0px 1px 2px 0px rgba(0, 0, 0, 0.30)',
                'level-2': '0px 2px 6px 2px rgba(0, 0, 0, 0.15), 0px 1px 2px 0px rgba(0, 0, 0, 0.30)',
                'level-3': '0px 4px 8px 3px rgba(0, 0, 0, 0.15), 0px 1px 3px 0px rgba(0, 0, 0, 0.30)',
                'level-4': '0px 6px 10px 4px rgba(0, 0, 0, 0.15), 0px 2px 3px 0px rgba(0, 0, 0, 0.30)',
                'level-5': '0px 8px 12px 6px rgba(0, 0, 0, 0.15), 0px 4px 4px 0px rgba(0, 0, 0, 0.30)',
            },
        },
    },
    plugins: [],
}
